import type {ArgusFolder} from '../types';
import {optionalClient, raise, requireClient} from './client';
import {rowToFolder} from './mappers';
import type {FolderRow} from './rows';

export async function list(orgId: string): Promise<ArgusFolder[]> {
  const client = optionalClient();
  if (!client) {
    return [];
  }
  const {data, error} = await client
      .from('folders')
      .select('id,org_id,name,parent_id,created_at')
      .eq('org_id', orgId)
      .order('created_at', {ascending: true});
  raise(error, 'folders.list');
  return ((data || []) as unknown as FolderRow[]).map(rowToFolder);
}

// The id is generated by the caller (crypto.randomUUID) rather than by the
// column default, because the UI selects the new folder immediately.
export async function create(orgId: string, folder: ArgusFolder): Promise<void> {
  const client = requireClient();
  const {error} = await client.from('folders').insert({
    id: folder.id,
    org_id: orgId,
    name: folder.name,
    created_at: folder.created_at || new Date().toISOString(),
  });
  raise(error, 'folders.create');
}

export async function rename(orgId: string, id: string, name: string): Promise<void> {
  const client = requireClient();
  const {error} = await client
      .from('folders')
      .update({name})
      .eq('org_id', orgId)
      .eq('id', id);
  raise(error, 'folders.rename');
}

// Profiles in this folder are moved to "All profiles" by the FK's
// ON DELETE SET NULL -- no second statement needed.
export async function remove(orgId: string, id: string): Promise<void> {
  const client = requireClient();
  const {error} = await client
      .from('folders')
      .delete()
      .eq('org_id', orgId)
      .eq('id', id);
  raise(error, 'folders.remove');
}
